name: flutter_native
description: A CLI making it easy to modify android and iOS contents
version: 0.1.0
maintainer: Deepraj Baidya <@deepraj02>
repository: https://github.com/deepraj02/flutter_native
issue_tracker: https://github.com/deepraj02/flutter_native/issues


environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ">=0.3.0 <0.5.0"
  mason_logger: ^0.2.4
  pub_updater: ">=0.2.4 <0.4.0"

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ">=3.1.0 <5.0.0"

executables:
  fnative: fnative
